'use strict';

import * as store from 'store2';

class Storage {

  constructor() {
    this.localeList = ['en', 'ru'];
    this._siteLanguage = store.get("siteLanguage", "en");
    
    this._propsMap = new Map();
    this._propsMap.set( "Americano", {"en" : "<strong>Caffè Americano</strong> is a style of coffee prepared by brewing espresso with added hot water, giving it a similar strength to, but different flavor from drip coffee. The strength of an Americano varies with the number of shots of espresso and the amount of water added", "ru" : "<strong>Американо</strong> &ndash; способ приготовления кофе, заключающийся в добавлении определённого количества горячей воды в эспрессо. Это позволяет получить менее крепкий (в зависимости от соотношения кофе и воды), чем классический эспрессо, напиток."} );
    this._propsMap.set( "Cappuccino", {"en" : "<strong>Cappuccino</strong> is an Italian coffee drink that is traditionally prepared with espresso, hot milk, and steamed milk foam.<br> Cream may be used instead of milk and is often topped with cinnamon. It is typically smaller in volume than a caffè latte, with a thicker layer of micro foam.", "ru" : "<strong>Капучино</strong> &ndash; кофейный напиток итальянской кухни на основе молока с добавлением сиропа и молочной пенки.<br> Происхождение названия напитка связано с тем, что в Европе XVII века название ордена капуцинов служило, в частности, и для обозначения характерного цвета (красно-коричневого), который имели рясы монахов этого ордена."} );
    this._propsMap.set( "Corretto", {"en" : "<strong>Caffè corretto</strong>, an Italian beverage, consists of a shot of espresso with a small amount of liquor, usually grappa, and sometimes sambuca or brandy. It is also known (outside Italy) as an \"espresso corretto\".<br> Most Italian bartenders prepare a caffè corretto simply adding a few drops of the desired liquor into an espresso shot.", "ru" : "<strong>Корретто</strong> &ndash; напиток итальянского происхождения, на основе кофе с добавлением ликера. Готовится из эспрессо с добавлением ликера, обычно с граппой, но иногда с самбукой или бренди."} );
    this._propsMap.set( "Doppio", {"en" : "<strong>Doppio</strong> in espresso is a double shot, extracted using a double coffee filter in the portafilter. This results in 60 ml of drink, double the amount of a single shot espresso.<br> More commonly called a standard double, it is a standard in judging the espresso quality in barista competitions.", "ru" : "<strong>Доппио</strong> &ndash; это кофе эспрессо, который приготовлен с помощью двойного количество молотого кофе и объема воды. Однако, не стоит путать с двойным эспрессо, где обычные две «соло» порции готовятся в одну кружку.<br> Эспрессо доппио &ndash; это двойной по крепости в объеме одной порции в маленькой кофейной чашечке."} );
    this._propsMap.set( "Espresso", {"en" : "<strong>Espresso</strong> is coffee brewed by forcing a small amount of nearly boiling water under pressure through finely ground coffee beans. Espresso is generally thicker than coffee brewed by other methods, has a higher concentration of suspended and dissolved solids, and has crema on top (a foam with a creamy consistency). As a result of the pressurized brewing process, the flavors and chemicals in a typical cup of espresso are very concentrated.", "ru" : "<strong>Эспрессо</strong> («под давлением») &ndash;  метод приготовления путём пропускания горячей (около 90 °C) и находящейся под давлением 9 бар воды через фильтр с молотым кофе.<br> Напиток пользуется огромной популярностью во всём мире и, прежде всего, на юге Европы — в Италии и Португалии."} );
    this._propsMap.set( "Glace", {"en" : "<strong>Glace</strong>.<br> Combine the coffee and 3 tbsp of warm water in a small bowl, mix well and keep aside.<br> Sieve the icing sugar in a deep bowl and gradually add the coffee-water mixture and mix very well till smooth.<br> Use immediately.", "ru" : "<strong>Глясе</strong> &ndash; холодный напиток на основе кофе с добавлением мороженого. В качестве посуды обычно используется стеклянный стакан или фужер.<br> Неизвестно, когда был изобретен рецепт глясе, однако принято считать, что его родина – это Австрия."} );
    this._propsMap.set( "Irish", {"en" : "<strong>Irish coffee</strong>  is a cocktail consisting of hot coffee, Irish whiskey, and sugar (some recipes specify that brown sugar should be used), stirred, and topped with thick cream. The coffee is drunk through the cream. The original recipe explicitly uses cream that has not been whipped, although drinks made with whipped cream are often sold as \"Irish coffee\".", "ru" : "<strong>Кофе по-ирландски</strong> &ndash;  кофейный напиток, который также можно отнести к категории коктейлей со сливками.<br> В специальный стеклянный сосуд ёмкостью около 150 см³ вливают горячий чёрный кофе. Добавляют в него сахарный песок и размешивают ложкой до полного растворения сахара. Затем вливают виски и украшают коктейль взбитыми сливками, переложив их «шапкой» на поверхность напитка."} );
    this._propsMap.set( "Latte", {"en" : "<strong>Latte</strong> is a coffee drink made with espresso and steamed milk. The drink is similar to a cappuccino, the difference being that a cappuccino consists of espresso and steamed milk with a 20 mm thick layer of milk foam.<br> A variant found in Australia and New Zealand similar to the latte is the flat white, which is served in a smaller ceramic cup with the micro-foamed milk.<br> In the United States this beverage is sometimes referred to as a wet cappuccino.", "ru" : "<strong>Латте</strong> &ndash; кофейный напиток родом из Италии, состоящий из молока (итал. latte) и кофе эспрессо.<br> Существуют варианты напитка, в состав которого вместо кофе входят чай, мате или маття."} ); 
    this._propsMap.set( "Lungo", {"en" : "<strong>Lungo</strong> is a coffee beverage made by using an espresso machine to make an Italian-style coffee – short black (single or double dose or shot) with much more water (generally twice as much), resulting in a stretched coffee, a lungo.", "ru" : "<strong>Лунго</strong> &ndash; напиток из кофе, приготовленный с помощью кофе-машины по аналогии с эспрессо, но с гораздо большим количеством воды.<br> Обычный эспрессо готовится от 18 до 30 секунд и имеет объём от 25 до 30 миллилитров, в то время как приготовление лунго может занять до одной минуты, и имеет объём около 50 миллилитров."} );
    this._propsMap.set( "Macchiato", {"en" : "<strong>Caffè macchiato</strong> is an espresso coffee drink with a small amount of milk, usually foamed. In Italian, macchiato means \"stained\" or \"spotted\" so the literal translation of caffè macchiato is \"stained coffee\", or coffee with a spot of milk.", "ru" : "<strong>Макиато</strong> &ndash; кофейный напиток, изготавливаемый из порции эспрессо и небольшого количества молока, обычно взбитого. Также известен как эспрессо макиато.<br> Как и капучино, макиато является основой для латте-арта."} );
    this._propsMap.set( "Marocchino", {"en" : "<strong>Marocchino</strong> is a coffee drink created in Alessandria, Italy.<br> It is served in a small glass and consists of a shot of espresso (a small shot, or ristretto), cocoa powder and milk froth.", "ru" : "<strong>Марокино</strong> &ndash; это, по сути, миникапучино, в его состав входит эспрессо и вспененное молоко. Украшается какао-порошком и жидким шоколадом, подаётся в маленькой стеклянной чашке с металлической ручкой. "} );
    this._propsMap.set( "Mocha", {"en" : "<strong>Caffè mocha</strong> is based on espresso and hot milk, but with added chocolate, typically in the form of sweet cocoa powder, although many varieties use chocolate syrup. Mochas can contain dark or milk chocolate.", "ru" : "<strong>Мокко</strong> &ndash; разновидность кофе «арабика», названная по портовому городу на Красном море — Моха."} );
    this._propsMap.set( "Piccolo", {"en" : "<strong>Piccolo</strong> is a ristretto shot (15 – 20 ml) topped with warm, silky milk served in a 100 ml glass demitasse (small latte glass) basically, a baby latte, as the Italian pronunciation suggests.", "ru" : "<strong>Пикколо</strong> &ndash; кофейно-молочный напиток небольшого объёма. В оригинальном рецепте состоит из одного эспрессо и 70 мл взбитого паром однородного, глянцевого молока, подаётся в стекляном стаканчике объёмом 100 мл типа виски-шот.<br> В настоящее время более популярна вариация с двойным ристретто, верхом шика считается подача в мерном стаканчике."} );
    this._propsMap.set( "Ristretto", {"en" : "<strong>Ristretto</strong> is traditionally a short shot of espresso coffee made with the normal amount of ground coffee but extracted with about half the amount of water.<br> Since ristrettos are essentially the first half of a full length extraction, the faster-to-extract compounds predominate in a ristretto. The opposite of a ristretto is a lungo, which is typically double the shot volume. Ristretto means \"limited\" or \"restricted\" in Italian whereas lungo means \"long.\"", "ru" : "<strong>Ристретто</strong> &ndash; крепкий кофе, который готовится в объеме меньшем, чем эспрессо. Как правило, для приготовления такого напитка требуется 7 г кофе на 15-20 мл воды.<br> Согласно традиции, при подаче ристретто также подается стакан с холодной питьевой водой. Такой своеобразный ритуал преследует две цели: во-первых, это предотвращает обезвоживание организма. Во-вторых, вода помогает очищать вкусовые рецепторы, благодаря чему каждый новый глоток воспринимается как первый."} );
    this._propsMap.set( "Romano", {"en" : "<strong>Romano</strong>  is a shot of espresso with a slice of lemon served on the side. The lemon can be run along the rim of the cup as a way to accentuate the espresso's sweetness.<br> Despite the name, it has no link to Italy nor Rome.", "ru" : "<strong>Романо</strong> &ndash; это крепкий кофе, который обладает особым бодрящим воздействием, а также острым цитрусовым вкусом.<br> Для того, чтобы получить эспрессо романо, достаточно взять чашку крепкого эспрессо и добавить в напиток дольку лимона."} );
  }

  get siteLanguage() {
    return this._siteLanguage;
  }
  
  set siteLanguage(newValue) {
    if( ~this.localeList.indexOf(newValue) ) {
      store.set("siteLanguage", newValue);
      this._siteLanguage = newValue;
    }
  }
  
  get propsMap() {
    return this._propsMap;
  }

}

export default Storage;
